CREATE TABLE posts
( id BIGSERIAL PRIMARY KEY UNIQUE
, publish_date TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
, title VARCHAR(255) NOT NULL
, body TEXT NOT NULL
, author_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);
