CREATE TABLE events
( id BIGSERIAL PRIMARY KEY
, user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
, title VARCHAR(255) NOT NULL
, description VARCHAR(255) NOT NULL
, datetime TIMESTAMP WITHOUT TIME ZONE DEFAULT now() NOT NULL
);
